
version: 0.0
os: linux
files:
  - source: /codedeploy_files/index.html
    destination: /var/www/block-chain360.com/public_html/
hooks:
  BeforeInstall:
    - location: deploy/before_install
      timeout: 300
      runas: root
  AfterInstall:
    - location: deploy/restart_server
      timeout: 300
      runas: root
